#version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - SQL_HOST=mysql
      - SQL_USERNAME=${SQL_USERNAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=${SQL_PORT}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    ports:
      - ${SQL_EXPOSE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_PASSWORD}
      MYSQL_DATABASE: ${SQL_DATABASE}
    volumes:
      - mysql_data_0612:/var/lib/mysql
  
  polling:
    image: polling:1.2.2
    environment:
      - SQL_HOST=mysql
      - SQL_USERNAME=${SQL_USERNAME}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_PORT=${SQL_PORT}
    depends_on:
      - mysql
      - backend

volumes:
  mysql_data_0612:
