export enum TxLogDomain {
  STUDENT_REGISTER = 'STUDENT_REGISTER',
  ADMIN_REGISTER = 'ADMIN_REGISTER',
  MILEAGE_SUBMIT = 'MILEAGE_SUBMIT',
  MILEAGE_APPROVE = 'MILEAGE_APPROVE',
  MILEAGE_REJECT = 'MILEAGE_REJECT',
  MILEAGE_MINT = 'MILEAGE_MINT',
  MILEAGE_BURN = 'MILEAGE_BURN',
  MILEAGE_TOKEN_CREATE = 'MILEAGE_TOKEN_CREATE',
  WALLET_CHANGE = 'WALLET_CHANGE',
}
